# Generated by Django 5.0.1 on 2024-01-09 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["id"]},
        ),
    ]
